version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker-publish: circleci/docker-publish@0.1.7
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            #- run: npm test
      
workflows:
    build-and-test:
      jobs:
        - build-and-test
    build-and-publish-docker-image:
      jobs:
        - docker-publish/publish:
            image: todarch/web
            tag: $CIRCLE_BUILD_NUM